# Generated by Django 5.1.5 on 2025-01-30 01:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_review"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author",
            old_name="first_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="author",
            name="last_name",
        ),
    ]
