# Generated by Django 5.1.5 on 2025-02-03 01:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0009_shelf_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
