# Generated by Django 5.1.5 on 2025-02-04 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0010_alter_book_isbn"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shelf",
            name="books",
        ),
        migrations.RemoveField(
            model_name="list",
            name="books",
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("publication_date", models.DateField()),
                ("isbn", models.CharField(max_length=13, unique=True)),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("book", "Book"),
                            ("ebook", "Ebook"),
                            ("audiobook", "Audiobook"),
                        ],
                        default="book",
                        max_length=20,
                    ),
                ),
                ("pages", models.IntegerField()),
                ("cover_image", models.ImageField(blank=True, upload_to="covers/")),
                ("summary", models.TextField(blank=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="books.author",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="list",
            name="media",
            field=models.ManyToManyField(related_name="lists", to="books.media"),
        ),
        migrations.AddField(
            model_name="shelf",
            name="media",
            field=models.ManyToManyField(related_name="shelves", to="books.media"),
        ),
        migrations.AlterField(
            model_name="review",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="books.media",
            ),
        ),
        migrations.DeleteModel(
            name="Book",
        ),
    ]
